"""Persisted, spaced-repetition-scheduled flashcards — distinct from the
ephemeral flashcards generated by /notes/{id}/flashcards (which are a quick
disposable study aid, never saved). A card only exists here once the student
explicitly chooses to save a generated set for review. Scheduling fields
follow the standard SM-2 algorithm (see services/note_flashcard_service.py)."""

from __future__ import annotations

from datetime import UTC, datetime

from beanie import Document, PydanticObjectId
from pydantic import Field
from pymongo import IndexModel


class NoteFlashcard(Document):
    userId: PydanticObjectId
    noteId: PydanticObjectId
    front: str
    back: str
    easeFactor: float = 2.5
    intervalDays: int = 0
    repetitions: int = 0
    # Due immediately on creation — a freshly saved card is ready to review right away.
    dueAt: datetime = Field(default_factory=lambda: datetime.now(UTC))
    lastReviewedAt: datetime | None = None
    createdAt: datetime = Field(default_factory=lambda: datetime.now(UTC))

    class Settings:
        name = "noteflashcards"
        indexes = [IndexModel([("userId", 1), ("dueAt", 1)]), IndexModel([("noteId", 1)])]
