/**
 * Canonical error codes used in ApiErrorResponse.error.code across the stack.
 */
export const ERROR_CODES = {
  NOT_FOUND: "NOT_FOUND",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHENTICATED: "UNAUTHENTICATED",
  UNAUTHORIZED: "UNAUTHORIZED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  CONFLICT: "CONFLICT",
  RATE_LIMITED: "RATE_LIMITED",
  INVALID_STATE_TRANSITION: "INVALID_STATE_TRANSITION",
  INTEGRATION_ERROR: "INTEGRATION_ERROR",
  PLAN_LIMIT_EXCEEDED: "PLAN_LIMIT_EXCEEDED",
  AI_PROVIDER_ERROR: "AI_PROVIDER_ERROR",
  EMAIL_PROVIDER_ERROR: "EMAIL_PROVIDER_ERROR",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
