import { Router } from "express";
import { authRouter } from "./auth.routes.js";
import { healthRouter } from "./health.routes.js";
import { contactRouter } from "./contact.routes.js";
import { templateRouter } from "./template.routes.js";
import { integrationRouter } from "./integration.routes.js";
import { campaignRouter } from "./campaign.routes.js";
import { trackingRouter } from "./tracking.routes.js";
import { analyticsRouter } from "./analytics.routes.js";
import { userContextRouter } from "./userContext.routes.js";
import { usageRouter } from "./usage.routes.js";
import { auditRouter } from "./audit.routes.js";
import { notificationRouter } from "./notification.routes.js";
import { resumeRouter } from "./resume.routes.js";
import { careerFitRouter } from "./careerFit.routes.js";
import { roadmapRouter } from "./roadmap.routes.js";
import { codeSandboxRouter } from "./codeSandbox.routes.js";
import { jobRouter } from "./job.routes.js";
import { discussionRouter } from "./discussion.routes.js";
import { mockInterviewRoomRouter } from "./mockInterviewRoom.routes.js";
import { feedbackRouter } from "./feedback.routes.js";
import { jobIntelRouter } from "./jobIntel.routes.js";
import { outreachDraftRouter } from "./outreachDraft.routes.js";
import { jobLeadRouter } from "./jobLead.routes.js";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/contacts", contactRouter);
apiRouter.use("/templates", templateRouter);
apiRouter.use("/integrations", integrationRouter);
apiRouter.use("/campaigns", campaignRouter);
apiRouter.use("/t", trackingRouter);
apiRouter.use("/analytics", analyticsRouter);
apiRouter.use("/profile/context", userContextRouter);
apiRouter.use("/usage", usageRouter);
apiRouter.use("/audit-logs", auditRouter);
apiRouter.use("/notifications", notificationRouter);
apiRouter.use("/resumes", resumeRouter);
apiRouter.use("/career-fit", careerFitRouter);
apiRouter.use("/roadmaps", roadmapRouter);
apiRouter.use("/code", codeSandboxRouter);
apiRouter.use("/jobs", jobRouter);
apiRouter.use("/discussions", discussionRouter);
apiRouter.use("/mock-interview", mockInterviewRoomRouter);
apiRouter.use("/feedback", feedbackRouter);
apiRouter.use("/job-intel", jobIntelRouter);
apiRouter.use("/outreach-drafts", outreachDraftRouter);
apiRouter.use("/job-leads", jobLeadRouter);
